const caps = {
  title: [
    "Top Level Baseball Cap Men Women - Classic Adjustable Plain Hat",
    "Top Level Baseball Cap Men Women - Classic Adjustable Plain Hat",
    "Top Level Baseball Cap Men Women - Classic Adjustable Plain Hat",
    "Top Level Baseball Cap Men Women - Classic Adjustable Plain Hat",
    "Top Level Baseball Cap Men Women - Classic Adjustable Plain Hat",
    "Top Level Baseball Cap Men Women - Classic Adjustable Plain Hat",
    "Top Level Baseball Cap Men Women - Classic Adjustable Plain Hat",
    "Top Level Baseball Cap Men Women - Classic Adjustable Plain Hat",
  ],
  imageCap: [
    "https://m.media-amazon.com/images/I/61j-nUQuKRL._AC_SX679_.jpg",
    "https://m.media-amazon.com/images/I/71Uh-djifIL._AC_SX679_.jpg",
    "https://m.media-amazon.com/images/I/71hBJJc3QYL._AC_SX679_.jpg",
    "https://m.media-amazon.com/images/I/71BydrIhpDL._AC_SX679_.jpg",
    "https://m.media-amazon.com/images/I/61xAlsRpXOL._AC_SX679_.jpg",
    "https://m.media-amazon.com/images/I/71Q0-0WYcqL._AC_SX679_.jpg",
    "https://m.media-amazon.com/images/I/71Oc4i8HAUL._AC_SX679_.jpg",
    "https://m.media-amazon.com/images/I/71vsdOPpxWL._AC_SX679_.jpg",
  ],
  size: [
    "One Size",
    "One Size",
    "One Size",
    "One Size",
    "One Size",
    "One Size",
    "One Size",
    "One Size",
  ],
  color: [
    "Black",
    "Dark Brown",
    "Dark Green",
    "Dark Grey",
    "Hot Pink",
    "Kelly Green",
    "Khaki",
    "Light Grey",
  ],
  price: ["9.99", "9.99", "9.99", "9.99", "9.99", "9.99", "9.99", "9.99"],
};
export default caps;
