const watches = {
  id: ["01", "02", "03", "04", "05", "06", "07", "08"],
  text: [
    "Fossil Grant Men's Watch with Chronograph or Automatic Display and Genuine Leather or Stainless Steel Band",
    "Fossil Grant Men's Watch with Chronograph or Automatic Display and Genuine Leather or Stainless Steel Band",
    "Fossil Grant Men's Watch with Chronograph or Automatic Display and Genuine Leather or Stainless Steel Band",
    "Fossil Grant Men's Watch with Chronograph or Automatic Display and Genuine Leather or Stainless Steel Band",
    "Fossil Grant Men's Watch with Chronograph or Automatic Display and Genuine Leather or Stainless Steel Band",
    "Fossil Grant Men's Watch with Chronograph or Automatic Display and Genuine Leather or Stainless Steel Band",
    "Fossil Grant Men's Watch with Chronograph or Automatic Display and Genuine Leather or Stainless Steel Band",
    "Fossil Grant Men's Watch with Chronograph or Automatic Display and Genuine Leather or Stainless Steel Band",
  ],
  image: [
    "https://m.media-amazon.com/images/I/71UIocsjBUL._AC_SX679_.jpg",
    "https://m.media-amazon.com/images/I/81jfnE4YGLL._AC_SX679_.jpg",
    "https://m.media-amazon.com/images/I/713EyiqlnTL._AC_SX679_.jpg",
    "https://m.media-amazon.com/images/I/71EkzrwiU6L._AC_SX679_.jpg",
    "https://m.media-amazon.com/images/I/71VqwTO4efL._AC_SX679_.jpg",
    "https://m.media-amazon.com/images/I/71bIzlId7-L._AC_SX679_.jpg",
    "https://m.media-amazon.com/images/I/71Z5n0DTigL._AC_SX679_.jpg",
    "https://m.media-amazon.com/images/I/818lBoWqXtL._AC_SX679_.jpg",
  ],
  price: [
    "64.00",
    "157.41",
    "64.00",
    "68.69",
    "98.19",
    "64.00",
    "97.39",
    "84.52",
  ],
  color: [
    "Black/Silver",
    "Blue, Black",
    "Brown",
    "Rose Gold, Blue",
    "Silver",
    "Brown",
    "Silver, Brown Automatic",
    "Silver/Blue",
  ],
};
export default watches;
